---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus-ingress
  namespace: gatus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  rules:
  - host: gatus.v34l.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gatus
            port:
              number: 80
  tls:
    - hosts:
      - gatus.v34l.com
      secretName: gatus-secret
