apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: v34l-blog-app
  namespace: hugo
resources:
  - base/deployment.yaml
  - base/service.yaml
  - resources/ingress.yaml
  - resources/default-ingress.yaml
